<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591;1573</NoWarn>

    <RootNamespace>GroveGames.Tween</RootNamespace>
    <Company>Grove Games</Company>
    <Authors>Grove Games</Authors>
    <Copyright>© $([System.DateTime]::Now.ToString("yyyy")) Grove Games</Copyright>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
    <Version>0.0.1</Version>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageProjectUrl>https://github.com/grovegs/Tween</PackageProjectUrl>
    <RepositoryUrl>https://github.com/grovegs/Tween</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Lightweight Tween library for Godot C#</Description>
    <PackageTags>godot;tween;grovegames</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <Using Include="System" />
    <Using Include="System.Buffers" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Globalization" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)Icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="all" />
  </ItemGroup>
</Project>
