name: 🧪 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NAME: ${{ vars.PROJECT_NAME }}
  AUTHOR: ${{ vars.PROJECT_AUTHOR }}

jobs:
  core_tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: ✅ Test Dotnet
        uses: grovegs/actions/.github/actions/test-dotnet@main
        with:
          project: tests/$AUTHOR.$NAME.Tests/$AUTHOR.$NAME.Tests.csproj

  godot_tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: ✅ Test Dotnet
        uses: grovegs/actions/.github/actions/test-dotnet@main
        with:
          project: tests/$AUTHOR.$NAME.Godot.Tests/$AUTHOR.$NAME.Godot.Tests.csproj
